<?php
/**
 * Подключили ajax библиотеку, скрипты и стили для работы модуля
 */
function ajaxcontent_init() {
  drupal_add_library('system', 'drupal.ajax');
  drupal_add_css(drupal_get_path('module', 'ajaxcontent') .'/css/ajaxcontent.css');
  drupal_add_js(drupal_get_path('module', 'ajaxcontent') .'/js/ajaxcontent.js');
}

/**
 * Implements hook_menu()
*/
function ajaxcontent_menu() {
  $items['ajaxcontent'] = array(
    'page callback' => 'ajax_link_response',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  $items['admin/config/user-interface/ajaxcontent/settings'] = array(
    'title' => 'Settings Ajax Content',
    'description' => 'Settings for module Ajax Content',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ajaxcontent_admin_settings'),
    'file' => 'ajaxcontent.admin.inc',
    'file_path' => drupal_get_path('module', 'system')
  );
  return $items;
}

/**
 * Отдаем полученный результат браузеру
 */
function ajax_link_response($type = 'ajax', $nid = 0) {
  $output = _ajaxcontent_load_noder($nid);
  if($type == 'ajax'){
    $commands = array();
    $commands[] = ajax_command_replace('.wrapperAjaxcontent.none', '<div class="wrapperAjaxcontent visible"><div id="ajaxcontent"><div class="close">x</div>' . $output . '</div></div>');
    $page = array(
      '#type' => 'ajax',
      '#commands' => $commands
    );
    ajax_deliver($page);
  }else{
    $output = '<div id="ajaxcontent">' . $output . '</div>';
    return $output;
  }
}

/**
 * Получаем содержимое ноды и возвращаем HTML
 */
function _ajaxcontent_load_noder($nid = 0) {
  // загрузили ноду
  $node = node_load($nid, NULL, false);
  
  if ($node) {
    
    $vnode = node_view($node);
    $comment = variable_get('comment');
    if(!empty($comment) && $comment == 'yes'){
      $vnode['comments'] = comment_node_page_additions($node);
      return drupal_render($vnode);
    }else{
      return theme("node", $vnode);
    }
    
  }
}

/**
 * Implements hook_preprocess_html().
 */
function ajaxcontent_preprocess_html(&$vars){ 
  //$test = variable_get('comment', '');
  //krumo($test);
  $vars['page']['page_top'][] = array('ajaxcontent' => array('#markup' => '<div class="wrapperAjaxcontent none"><div id="ajaxcontent"></div></div>'));
}